server:
  port: 9999

spring:
  application:
    name: @pom.artifactId@

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:9000/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}



