server:
  port: 9100

spring:
  application:
    name: @pom.artifactId@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cn595980161/springCloudShop.git
          username:
          password:
          search-paths:


eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}



