server:
  port: 9001

spring:
  application:
    name: @pom.artifactId@

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
#  client:
#    serviceUrl:
#      defaultZone: http://root:root@localhost:9000/eureka

